rcaloras/bash-preexec

bash-preexec.sh

very minor, the loop var wasn't actually being unset because of a name mismatch

fix localized loop var typo

---

bash-preexec.sh

Tested with:
```sh
% bash --version
GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

test precmd_function without test compound command and command substitution

---

bash-preexec.sh

Tested with:
```sh
% bash --version
GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

test preexec_function without test compound command and command substitution

---

bash-preexec.sh

Tested with:
```sh
% bash --version
GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Store existing PROMPT_COMMAND without subshells

---

bash-preexec.sh
test/bash-preexec.bats
test/include-test.bats

Install bash-preexec after our session is started.
- Invoke our install as part of PROMPT_COMMAND. This allows bash-preexec to be
included at any point in our configuration and it should be invoked last.
This makes sure we always have access to the DEBUG trap and that
PROMPT_COMMAND is most likely untampered with.
- Should adress #21 and the occasional issue that gets created because
bash-preexec is included improperly.

Include order

---

bash-preexec.sh
test/bash-preexec.bats

`$_` should give the last argument of the last command. 
Currently it gives `__bp_preexec_invoke_exec`:
```
$ exec bash
$ . ./bash-preexec.sh
$ preexec() { echo "just typed $1"; }
$ echo $_
just typed echo $_
__bp_preexec_invoke_exec
$
```
Fix this to produce the expected behaviour:
```
exec bash
$ . ./bash-preexec.sh
$ preexec() { echo "just typed $1"; }
$ echo $_
just typed echo $_
./bash-preexec.sh
```
Note that `bash-bats` currently suffers from the *same bug* (it's a **feature** of bash), so the newly added test fails. I have manually tested it and it passes.

Don't clobber $_

---

bash-preexec.sh

This change causes `__bp_preexec_invoke_exec()` to return with the value from the last function in `preexec()`.  As of Bash 3.0 if `extdebug` is set a non-zero return value will cause the next command to be skipped.
http://git.savannah.gnu.org/cgit/bash.git/tree/NEWS#n1001

Preserve return value of last function in preexec()

---

bash-preexec.sh

Fixing a bug I introduced in #36. If `preexec_functions` was empty, the following error would occur.
```sh
bash-4.4$ source bash-preexec.sh 
bash-4.4$ true
bash: return: bash-preexec.sh: numeric argument required
bash-4.4$ 
```
I wasn't able to find a way to write a test for this behavior in Bats, if you have any idea how to observe the error within Bats let me know.

Initalize preexec_ret_value to prevent error

---

bash-preexec.sh
test/bash-preexec.bats

Before:
```sh
$ source bash-preexec.sh
$ PROMPT_COMMAND="$PROMPT_COMMAND; true"
bash: PROMPT_COMMAND: line 3: syntax error near unexpected token `;;'
bash: PROMPT_COMMAND: line 3: `__bp_precmd_invoke_cmd;  __bp_interactive_mode;; true'
$ 
```
After:
```sh
$ source bash-preexec.sh
$ PROMPT_COMMAND="$PROMPT_COMMAND; true"
$ declare -p PROMPT_COMMAND
declare -- PROMPT_COMMAND="__bp_precmd_invoke_cmd;  __bp_interactive_mode; true"
$ 
```

Remove trailing semicolon to allow appending to PROMPT_COMMANDS

---

bash-preexec.sh

Some friends and I are using bash-preexec in an application wherein our users sometimes load multiple projects that depend on bash-preexec in their shells. One of these uses extdebug, along with the useful feature that the command the user tries to run is skipped if the last function in preexec_functions returns an error - but we run into problems where the last function in preexec ends up being, eg, one that always returns 0, because the user also sources another script which tacks an extra function onto the end of preexec_functions.
This script changes the behavior of bash-preexec so that an error from any function in the array causes the overall debug trap call to return 1, so that extdebug can be used reliably in conjunction with multiple projects that use bash-preexec.

Change to preexec function error code

---

test/bash-preexec.bats

* There's no point checking $output if run isn't being called.
* Need to eval the value of $PROMPT_COMMAND separately from updating it.
See https://github.com/rcaloras/bash-preexec/commit/64c6f53b52#commitcomment-23327269

Fix two tests in bash-preexec.bats.

---

bash-preexec.sh
test/bash-preexec.bats
test/include-test.bats

* Capture any pre-existing PROMPT_COMMAND hook in the same way, adding it as a precmd function.
* No longer need to do string manipulations of the PROMPT_COMMAND's contents.
* Added a unit test of the new trapping semantics.
* Tidied up some other tests to test the public API and avoid tweaking internal state
(e.g. the old $_ test would fail to catch a bug in this change).
Resolves issue #39.

Ensure a pre-existing DEBUG trap is preserved as a preexec function.

---

bash-preexec.sh

- This was causing crashes in cases where users were doing:
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND;"
- Original description from contributor:
$(trap -p DEBUG)" is launching a sub-shell, bash itself. So when people do
"export PROMPT_COMMAND="history -a; $PROMPT_COMMAND;"", they export form the
parent shell to subsequent sub-shells. And that creates the infinite loop,
that eventually segfault bash.

Remove saving prior trap in PROMPT_COMMAND with subshell

---

bash-preexec.sh
test/bash-preexec.bats

- Fixes bug where IFS in outer environment could be set to something that
would cause our inner functions to break on varibale expansion.
- Added a couple unit tests.

Fix #64 by quoting functions and set IFS on read

---

bash-preexec.sh

The `bash-preexec.sh` script is supposed to be sourced into a Bash and
never meant to be run as a standalone script. However, shebangs are
meant as a hint to the program loader to select the proper binary if
executing a text file as if it were one. Thus, the shebang in this
script will never be evaluated and might actually mislead users to
execute instead of source this script. Some distros frown at this.
E.g., openSUSE lints packages for such scripts and generates a warning.

Drop the misleading shebang

---

bash-preexec.sh
test/include-test.bats

Detect variables bash-preexec requires writable access to that have been marked readonly

---

.travis.yml

This is necessary for testing with 'nounset'.
Trying again independently of the other PR which also changes the tests, so as to see which change is actually breaking things.

upgrade Travis bats version to bats-core 1.1.0

---

bash-preexec.sh
test/bash-preexec.bats

This uses a sed-based regex instead of the read builtin to drop the initial number output by the 'history' command.
The problems with the read builtin are:
- It only reads a single line.
- It strips whitespace.
Changing to this sed expression (which removes the initial number from the first line only, assuming that the format of the history line is "%5d%c %s%s\n" as in history.def in the bash source code) resolves both of these issues, fixing #77 and #78 .
This also removes the need for either an echo or a printf, and so also incidentally resolves #76 . (As pointed out on that issue, this could also have been fixed without switching to sed.)
Adds regression tests for the fixed issues. The test code is also adjusted to not have the same echo/printf issue.

Fix issues with capturing certain commands

---

.travis.yml
bash-preexec.sh
test/bash-preexec.bats

As noted in #80 , the main actual issue here is that because we install a DEBUG trap, our code may run even in contexts where the user thinks they've set bash options for their own code only. As such, it would be nice if we were very well behaved.
It's easier to just run the tests entirely under this option -- that saves us from having to think about which code needs to be nounset-safe and which code does not.
The actual code changes are pretty trivial, it's just a matter of applying them consistently, which the tests will enforce. (For whatever version of bash is running on Travis, which currently is 4.3 . We should probably test multiple versions of bash.)
This is based off the upgrade-bats branch which was sent as a separate pull request; …

Compatibility with "nounset" bash option (fixed for bash 4.3)

---

bash-preexec.sh
test/bash-preexec.bats

Unfortunately, I couldn't figure out how to restore it for each
function, so I just made a copy in $BP_PIPESTATUS for those functions to
use.
For documentation of PIPESTATUS, see
https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#index-PIPESTATUS
Closes #81.

Save $PIPESTATUS for precmd and preexec functions to use.

---

bash-preexec.sh

1. Avoid using `\+` because it's not available on some BSDs.
2. Set the locale to avoid number formatting issues.

Miscellaneous fixes for sed.

---

test/README.md
test/bash-preexec.bats
test/include-test.bats

* Using `[[ ... ]]` on older versions of Bash (e.g. 3.2 on macOS) causes the test to always pass.
* Includes `test/README.md` that explains the problem and suggest solutions for future tests.

Change [[ to [ in tests where possible

---

bash-preexec.sh
test/bash-preexec.bats

In a [`--posix` shell](https://www.gnu.org/software/bash/manual/html_node/Bash-POSIX-Mode.html) (e.g. a shell invoked as `sh` instead of `bash`) the ARG parameter is not optional:
> 41. The trap builtin doesn’t check the first argument for a possible signal specification and revert the signal handling to the original disposition if it is, unless that argument consists solely of digits and is a valid signal number. If users want to reset the handler for a given signal to the original disposition, they should use ‘-’ as the first argument.
It may not be the intent of bash-preexec to actively _support_ POSIX mode, but the failure behavior here is pretty bad:
```
$ bash --noprofile --norc --posix || echo BASH CRASHED
bash-5.0$ source bash_preexec.sh
trap: usage: trap [-lp] [[arg] signal_spec …
```

Tweak the syntax for clearing the DEBUG trap

---

bash-preexec.sh
test/bash-preexec.bats

This change allows us to avoid unnecessary command substitutions which are (relatively speaking) quite expensive. Although `__bp_sanitize_string` is only used during installation `__bp_trim_whitespace` is invoked in a loop in the critical path as part of `__bp_preexec_invoke_exec`. Eliminating these subshells will reduce bash-preexec's overhead.
See https://github.com/dimo414/prompt.gem/commit/9764cdb3 for another example of a similar change.
Note: the `printf -v` syntax was added to Bash in v3.1: https://mywiki.wooledge.org/BashFAQ/061

Reimplement the string-manipulation functions to write to variables instead of stdout

---

bash-preexec.sh
test/bash-preexec.bats

- Return with an exit code of 1 when run in any shell other than Bash.
Should prevent any functions or variables from being defined. This check
was previously run later during initialization.
- Updated test case for this
- Should address #113

Return immediately when not run in Bash

---

bash-preexec.sh

Expressly handle if $PROMPT_COMMAND is previously undefined. This is a follow-on to #101. Alsö, declare the function arrays so that other scripts which depend on this one don't have to deal with them being unbound until the first prompt.

Handle unbound PROMPT_COMMAND

---

bash-preexec.sh
test/include-test.bats

Locally verified on macOS, with Bats from MacPorts.

Fix bugs in the code and in tests 

---

.github/workflows/bats.yaml

After this is verified to work, we can probably remove the Travis CI configuration.

Configure the first workflow for GitHub Actions

---

README.md
bash-preexec.sh
test/include-test.bats

This formally exposes it as part of the public API. RFC: @dimo414.
Fixes #122.

Remove the underscore prefix of `__bp_imported`

---

bash-preexec.sh
test/bash-preexec.bats

WIthout this change, `__bp_precmd_invoke_cmd` may not restore `$?` to its original value after being run.
Since `__bp_precmd_invoke_cmd` get installed as the first thing in `PROMPT_COMMAND`, this will cause problems if there is an existing `PROMPT_COMMAND` (which is perhaps not aware of `bash-preexec`) that wants to do something with the exit status of the command that was just run.

Return original value from `__bp_precmd_invoke_cmd`

---

bash-preexec.sh

Don't depend on running modern Bash/ksh/zsh when we're trying to detect if we're running a modern bash.

Use POSIX syntax for Bash detection

---

bash-preexec.sh

Hi,
I went ahead and fixed the shellcheck warnings mentioned in https://github.com/rcaloras/bash-preexec/issues/132
Changes to actual code were minimal (couple of quotes and a newline I think).
Test suite runs correctly on my system.
bats test
✓ sourcing bash-preexec should exit with 1 if we're not using bash 
✓ __bp_install should exit if it's already installed 
✓ __bp_install should remove trap logic and itself from PROMPT_COMMAND 
✓ __bp_install should preserve an existing DEBUG trap 
✓ __bp_sanitize_string should remove semicolons and trim space 
✓ Appending to PROMPT_COMMAND should work after bp_install 
✓ Appending or prepending to PROMPT_COMMAND should work after bp_install_after_session_init 
✓ Adding to PROMPT_COMMAND before and after initiating install 
✓ Adding to …

Update to remove shellcheck warnings

---

README.md
bash-preexec.sh
test/bash-preexec.bats

As discussed in https://github.com/rcaloras/bash-preexec/pull/129#issuecomment-1046169131 and https://github.com/rcaloras/bash-preexec/pull/129#issuecomment-1109971595, the current codebase relies on Bash 3.1 features. In this PR, I mention it in README and check the Bash version in the beginning of the script.

Check Bash version 3.1+

---

bash-preexec.sh

- 9c6e5d7 Maybe due to the difference of the shellcheck versions, but shellcheck-0.7.2 in my environment reports SC2034 also for this line.
- 84ef2b1 `disable=SC2034` has been applied to `__bp_last_ret_value` in addition to `BP_PIPESTATUS`. It would be better to apply it only for the intended variable, `BP_PIPESTATUS`.
- fffccd2 I noticed that `return "${1-}"` results in `return ''` and causes an error when `$1` is empty. This is a regression of #135. Instead, we should specify the argument as `${1:+"$1"}`.
- cb8048a This is also subject to word splitting by unexpected `IFS`. We want to quote it as well.
- 16e09f2 I think it is cleaner and readable for beginners to follow the suggestion from `shellcheck` rather than ignoring the warning

Addtional fixes for `shellcheck`

---

bash-preexec.sh

Some libraries do things like `PROMPT_COMMAND="$PROMPT_COMMAND ; _new_addition"`, that's a space-semicolon-space, and others do `PROMPT_COMMAND="_other_thing; $PROMPT_COMMAND"`. This leads to two consecutive semicolons if both libraries load after bp first sets `$PROMPT_COMMAND`. It would be counter-productive to try to account for all possibilities, so just swap the install string for a no-op. Then, try to clean up the no-op if it's all that's left.

Try to better handle external modification to `$PROMPT_COMMAND`

---

bash-preexec.sh
test/bash-preexec.bats

This is a fix for the issue I reported in https://github.com/rcaloras/bash-preexec/issues/130#issuecomment-1455852628.
ShellCheck seems to have started to complain about `-lt`, `-eq`, etc. in the conditional command `[[ ... ]]`, so I also included a commit (77aec5ff212daed4f0471264ee844c00cdaecc8d) to workaround the shellcheck warning.

Support the array PROMPT_COMMAND (bash >= 5.1)

---

bash-preexec.sh

I have separated this commit from #141 as suggested by @dimo414 (https://github.com/rcaloras/bash-preexec/pull/141#discussion_r1127193800).
As in the cover of #141, we seem to need to update the version check due to the shellcheck updates:
> *Quoted from https://github.com/rcaloras/bash-preexec/pull/141#issue-1612395608*
>
> ShellCheck seems to have started to complain about `-lt`, `-eq`, etc. in the conditional command `[[ ... ]]`, so I also included a commit ([77aec5f](https://github.com/rcaloras/bash-preexec/commit/77aec5ff212daed4f0471264ee844c00cdaecc8d)) to workaround the shellcheck warning.
Also
> *Quoted from https://github.com/rcaloras/bash-preexec/pull/141#discussion_r1127198702*
>
> I have introduced the version check in #136. At that time, I just used the single conditional …

Fix the test for the Bash version for shellcheck

---

bash-preexec.sh
test/include-test.bats

This just tests against the old internal-only guard. A possible enhancement would be to also generate an error message in this case, since the user probably wants to use the newer version rather than just silently being left with an old version.

Don't load if old version already present (Fixes rcaloras/bash-preexec#146)

---

test/bash-preexec.bats

This is an oversight of changing `trap DEBUG` to `trap - DEBUG` in
https://github.com/rcaloras/bash-preexec/pull/106
The oversight did not cause a test error because the test always succeeds.  The problem is that even if __bp_install is broken and fails to remove `trap - DEBUG`, the current test case failed to detect the failure and produce a false negative.  This PR fixes it.
----
This fix was first discussed in PR #129 and included as a part of PR #129. However, a reviewer doesn't seem to appear for PR #129, and PR #129 doesn't seem to be going to be merged currently. Because this fix is so trivial that I don't think there is a reason to block further, I separate the fix as an independent PR here.

Fix false-negative test case for __bp_install

---

bash-preexec.sh

Consider the following setup:
```bash
source bash-preexec.sh
function preexec { echo "==== $FUNCNAME ($1) ===="; }
function precmd { echo "==== $FUNCNAME ===="; }
function something { return 0; }
bind -x '"\C-t": something'
```
When I start a session with the above rcfile (`bashrc.exclude-bind-x`) and input <kbd>"echo 1" RET C-t "echo 2" RET C-d</kbd>, the result becomes this:
```bash
[murase@chatoyancy 1 bash-preexec]$ bash --rcfile bashrc.exclude-bind-x
==== precmd ====
[murase@chatoyancy 0 bash-preexec]$ echo 1
==== preexec (echo 1) ====
1
==== precmd ====
==== preexec (echo 1) ====
[murase@chatoyancy 0 bash-preexec]$ echo 2
2
==== precmd ====
[murase@chatoyancy 0 bash-preexec]$
exit
```
The second `preexec` is supposed to be called against the second command `echo 2`, but it's instead …

Exclude the `bind -x` commands from interactive commands

---

bash-preexec.sh

A few lines have the 2-space indentation. We fix them in this PR.
Also, several lines have suffix semicolons. Those semicolons might have been added by e.g. `bash --pretty-print bash-preexec.sh`, but we currently don't have such a semicolon for most of the lines anyway. There are two options for consistency:
- We suffix semicolons to every line that can have a semicolon.
- Or we remove all unnecessary semicolons.
In this PR, we choose the latter, the majority.

Fix indentation and remove trailing semicolons

---

.github/workflows/bats.yaml

20.04 runner has been deprecated.  For details see:
https://github.com/actions/runner-images/issues/11101

GitHub workflow: Update runner 20.04 -> 24.04

---

bash-preexec.sh
test/bash-preexec.bats

We use `trap` to bootstrap our installation function (__bp_install). We remove our code upon first execution but need to restore any preexisting trap calls. We previously used `sed` to process the trap string, but that had two downsides:
1. `sed` is an external command dependency. It needs to exist on the system, and we need to invoke it in a subshell (which has some runtime cost).
2. The regular expression pattern was imperfect and didn't handle trickier cases like `'` characters in the trap string:
$ (trap "echo 'hello'" DEBUG; trap -p DEBUG)
hello
trap -- 'echo '\''hello'\''' DEBUG
This change removes the dependency on `sed` by locally evaluating the trap string and extracting any prior trap. This works reliably because we control the format our trap string, which looks like this (with …

Improve prior_trap processing

---

bash-preexec.sh

We post-process `history 1`'s output to extract the current command. This processing needs to strip the leading history number, an optional `*` character indicating whether the entry was modified (or a space), and then a space separating character.
We were previously using sed(1) for this, but we can implement an equivalent transformation using bash's native parameter expansion syntax.
This also results in ~4x reduction in per-prompt command overhead.

Remove dependency on sed(1) for history processing
